# opt-in to Travis new infrastructure
sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.coursier

jdk:
- oraclejdk8
- oraclejdk9

language: scala
before_install:
  # Remove local .jvmopts file to run sbt-extras with
  # Travis default JVM options (stored in /etc/sbt/jvmopts)
  - rm .jvmopts
# 2.10.7 is needed for JDK 9 compat (can be removed once sbt 0.13.17 is out)
# keep heap usage down by running tests serially
script:
  - sbt -Dsbt.scala.version=2.10.7 'set parallelExecution in Test := false' +test scalastyle

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
