name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v8
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        jvm: 25
        apps: scala
    - uses: extractions/setup-just@v4
    - name: Test
      run: just
