name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Test
      # keep heap usage down by running tests serially
      run: sbt 'set Test / parallelExecution := false' +test
