name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 21
            os: ubuntu-latest
          - java: 21
            os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
    - run: git config --global core.autocrlf false  # for Windows
    - uses: actions/checkout@v3
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - name: Test
      # keep heap usage down by running tests serially
      run: sbt 'set Test / parallelExecution := false' +test
